services:
  - type: web
    name: portfolio-backend
    env: node
    buildCommand: cd portfolio-backend && npm ci
    startCommand: cd portfolio-backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Baddy:Shubh2408@cluster0.sgiw42d.mongodb.net/portfolio?retryWrites=true&w=majority  # Replace with your MongoDB Atlas URI
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        value: https://your-frontend-url.com  # Update this with your frontend URL
